# see CONTRIBUTING.md
---
version: '3'
services:
  mysql:
    image: ${MYSQL_IMAGE:-percona/percona-server}
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      - ${MYSQL_COMMAND:---verbose}
    ports:
      - 127.0.0.1:3306:3306
  mongodb:
    image: ${MONGODB_IMAGE:-percona/percona-server-mongodb}
    ports:
      - 127.0.0.1:27017:27017
